# This is a basic workflow to help you get started with Actions

name: Run task

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

env:
  SLACK_CHANNEL_URI: ${{ secrets.SLACK_CHANNEL_URI }}
  SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-site:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check azure storage blob
        env:
          URL_TO_CHECK: https://zbox2.blob.core.windows.net/static/index.html
        shell: powershell
        run: ./test200.ps1
      - name: Check azure CDN
        env:
          URL_TO_CHECK: https://www.dummyurl123.com
        shell: powershell
        run: ./test200.ps1
      - name: Check redirect
        env:
          URL_TO_CHECK: http://zbox.com
        shell: powershell
        run: ./test200.ps1
      - name: Check retrieving homepage category list
        env:
          URL_TO_CHECK: https://api.zbox.com/api/graphql
          QUERY_DESC: homepage category list
          QUERY_TO_CHECK: |
            {"query": "{ v1 { info { version zipCodeTemplate } categories { displayOrder id name seoName parentCategoryId showOnHomePage picture { thumbnail(size:100) { url } } } } }"}
        shell: powershell
        run: ./testgraphql.ps1
      - name: Check admin site
        env:
          URL_TO_CHECK: https://admin.zbox.com/Admin
        shell: powershell
        run: ./test200.ps1

